# make sure CI pulls submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

before_script:
  - export CARGO_HOME="${PWD}/.cargo"
  - export SCCACHE_DIR="${PWD}/.cache/sccache"

stages:
  - test
  - build
  - deploy

# make sure that formatting is correct.
rustfmt:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

# make sure there are no issues with the code.
clippy:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - cargo clippy

# run unit tests.
test:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  script:
    - cargo test

# generate release build
build:amd64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/storage
    expire_in: 1 week

# build for arm target
build:arm32:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm32
  stage: build
  script:
    - cargo build --release --target arm-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabihf/release/storage
    expire_in: 1 week

# build for arm target
build:arm64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm64
  stage: build
  script:
    - cargo build --release --target aarch64-unknown-linux-gnu
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/storage
    expire_in: 1 week

# generate rust html documentation
rustdoc:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

# publish binary, docs and API docs to gitlab pages.
pages:
  image: registry.gitlab.com/fractalnetworks/images/pages
  stage: deploy
  dependencies:
    - build:amd64
    - build:arm64
    - build:arm32
    - rustdoc
  script:
    - mkdir public
    - mv target/doc public/doc
    - mv target/release/storage public/storage-master-amd64
    - sign public/storage-master-amd64
    - mv target/arm-unknown-linux-gnueabihf/release/storage public/storage-master-arm32
    - sign public/storage-master-arm32
    - mv target/aarch64-unknown-linux-gnu/release/storage public/storage-master-arm64
    - sign public/storage-master-arm64
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master

docker:
  dependencies:
    - build:amd64
  image: docker
  stage: deploy
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
