# make sure CI pulls submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

before_script:
  - export CARGO_HOME="${PWD}/.cargo"
  - export SCCACHE_DIR="${PWD}/.cache/sccache"

stages:
  - test
  - build
  - publish
  - deploy

# make sure that formatting is correct.
check-formatting:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

# make sure there are no issues with the code.
check-mistakes:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  allow_failure: true
  script:
    - cargo clippy

# when pushing a tag, make sure that the tag version
# matches the version set in the Cargo.toml file.
check-version:
  image: debian:11
  stage: test
  script:
    - test $(sed -rn 's/^version = "(.+)"/v\1/p' Cargo.toml | head -n 1) = "$CI_COMMIT_TAG"
  rules:
    - if: $CI_COMMIT_TAG

# run unit tests.
test:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: test
  script:
    - cargo test

# generate release build
build:amd64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/storage
    expire_in: 1 week

# build for arm target
build:arm32:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm32
  stage: build
  script:
    - cargo build --release --target arm-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabihf/release/storage
    expire_in: 1 week

# build for arm target
build:arm64:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable-arm64
  stage: build
  script:
    - cargo build --release --target aarch64-unknown-linux-gnu
  artifacts:
    paths:
      - target/aarch64-unknown-linux-gnu/release/storage
    expire_in: 1 week

# generate rust html documentation
rustdoc:
  image: registry.gitlab.com/fractalnetworks/images/rust:stable
  stage: build
  script:
    - cargo doc --no-deps
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

# build docker image
docker:
  dependencies:
    - build:amd64
  image: registry.gitlab.com/fractalnetworks/images/docker
  stage: publish
  services:
    - docker:dind
  script:
    - ci-docker-build-push
  rules:
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH

# publish binary, docs and API docs to gitlab pages.
pages:
  image: registry.gitlab.com/fractalnetworks/images/pages
  stage: deploy
  dependencies:
    - build:amd64
    - build:arm64
    - build:arm32
    - rustdoc
  script:
    - mkdir public
    - mv target/doc public/doc
    - mv target/release/storage public/storage-amd64
    - sign public/storage-amd64
    - mv target/arm-unknown-linux-gnueabihf/release/storage public/storage-arm32
    - sign public/storage-arm32
    - mv target/aarch64-unknown-linux-gnu/release/storage public/storage-arm64
    - sign public/storage-arm64
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - main
