image: rustlang/rust:nightly

# make sure CI pulls submodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

# set up cache to speed up builds
cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .cargo/
    - .cache/sccache

before_script:
  - wget https://github.com/mozilla/sccache/releases/download/v0.2.15/sccache-v0.2.15-x86_64-unknown-linux-musl.tar.gz -O /tmp/sccache.tar.gz
  - tar -xf /tmp/sccache.tar.gz --strip-components=1 -C /usr/local/bin/
  - chmod +x /usr/local/bin/sccache
  - export CARGO_HOME="${PWD}/.cargo"
  - export SCCACHE_DIR="${PWD}/.cache/sccache"
  - export RUSTC_WRAPPER="/usr/local/bin/sccache"

stages:
  - test
  - build
  - deploy

# make sure that formatting is correct.
rustfmt:
  stage: test
  allow_failure: true
  script:
    - cargo fmt -- --check

# make sure there are no issues with the code.
clippy:
  stage: test
  allow_failure: true
  script:
    - cargo clippy

# run unit tests.
test:
  stage: test
  script:
    - cargo test

# generate release build
build:amd64:
  stage: build
  script:
    - cargo build --release
  artifacts:
    paths:
      - target/release/storage
    expire_in: 1 week

# build for arm target
build:arm:
  stage: build
  before_script:
    - apt update
    - apt install -y gcc-arm-linux-gnueabihf g++-arm-linux-gnueabihf
    - rustup target add arm-unknown-linux-gnueabihf
  script:
    - export CARGO_TARGET_ARM_UNKNOWN_LINUX_GNUEABIHF_LINKER=/usr/bin/arm-linux-gnueabihf-gcc
    - cargo build --release --target arm-unknown-linux-gnueabihf
  artifacts:
    paths:
      - target/arm-unknown-linux-gnueabihf/release/storage
    expire_in: 1 week

# generate rust html documentation
rustdoc:
  stage: build
  script:
    - cargo doc
  artifacts:
    paths:
      - target/doc
    expire_in: 1 week

# publish binary, docs and API docs to gitlab pages.
pages:
  stage: deploy
  dependencies:
    - build:amd64
    - build:arm
    - rustdoc
  script:
    - mkdir public
    - mv target/doc public/doc
    - mv target/release/storage public/storage-master-amd64
    - mv target/arm-unknown-linux-gnueabihf/release/storage public/storage-master-arm
  artifacts:
    paths:
      - public
    expire_in: 1 week
  only:
    - master

docker:
  dependencies:
    - build:amd64
    - build:arm
  image: docker:18.06
  stage: deploy
  services:
    - docker:18.06-dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build . -t "$CI_REGISTRY_IMAGE:latest"
    - docker push "$CI_REGISTRY_IMAGE:latest"
  only:
    - master
