[package]
name = "storage-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.2", default-features = false, features = ["stream", "rustls-tls", "json"] }
url = "2.2.1"
serde = { version = "1.0.124", features = ["derive"] }
async-trait = "0.1.48"
anyhow = "1.0.38"
structopt = { version = "0.3.21", optional = true }
tokio = { version = "1.3.0", optional = true }
byteorder = "1.4.3"
tokio-util = { version = "0.6.5", optional = true }
tokio-stream = { version = "0.1.5", optional = true }
bytes = "1.1.0"
futures = "0.3.13"
log = "0.4.14"
chacha20 = "0.8.0"
wireguard-keys = "0.1.0"
rand_core = { version = "0.5", features = ["getrandom"] }
ed25519-dalek-fiat = "0.1.0"
blake2 = "0.10.4"

[features]
default = ["tokio", "tokio-util/io", "tokio-stream"]
api = []
client = ["structopt", "tokio/rt-multi-thread", "tokio/macros", "tokio/io-std", "tokio/fs"]

[dev-dependencies]
tokio = { version = "1.3.0", features = ["full"] }

[[bin]]
name = "client"
required-features = ["client"]
