[package]
name = "storage-api"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11.2", features = ["stream", "rustls-tls", "json"] }
url = "2.2.1"
serde = { version = "1.0.124", features = ["derive"] }
async-trait = "0.1.48"
ed25519-dalek = "1.0.1"
rand_core = { version = "0.5", features = ["getrandom"] }
base64 = "0.13.0"
hex = "0.4.3"
anyhow = "1.0.38"
structopt = { version = "0.3.21", optional = true }
tokio = { version = "1.3.0", optional = true }
byteorder = "1.4.3"

[features]
default = []
client = ["structopt", "tokio/rt-multi-thread", "tokio/macros"]

[[bin]]
name = "client"
required-features = ["client"]
